services:
  web:
    build: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - database
  database:
    image: 'postgres' # use latest official postgres version
    ports:
      - 5432:5432
    env_file:
      - .env.database # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
