version: "3"
services:
  graphql:
    image: "timebook-graphql"
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: "postgresql://timebookdbuser:Test123@database:5432/timebookdb?schema=public"
    depends_on:
      - database
      - migrate
  migrate:
    image: "timebook-graphql"
    environment:
      DATABASE_URL: "postgresql://timebookdbuser:Test123@database:5432/timebookdb?schema=public"
    depends_on:
      - database
    command: npx prisma migrate dev
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - 5432:5432
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
