/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/catalogs/products': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List products
     * @description Lists products.
     */
    get: operations['products.list']
    put?: never
    /**
     * Create product
     * @description Creates a product.
     */
    post: operations['products.create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/catalogs/products/{product_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Show product details
     * @description Shows details for a product, by ID.
     */
    get: operations['products.get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update product
     * @description Updates a product, by ID. You can patch these attributes and objects:<table><thead><tr><th>Attribute or object</th><th>Operations</th></tr></thead><tbody><tr><td><code>description</code></td><td>add, replace, remove</td></tr><tr><td><code>category</code></td><td>add, replace, remove</td></tr><tr><td><code>image_url</code></td><td>add, replace, remove</td></tr><tr><td><code>home_url</code></td><td>add, replace, remove</td></tr></tbody></table>
     */
    patch: operations['products.patch']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    400: {
      details?: {
        /** @enum {string} */
        issue?: 'INVALID_PARAMETER_VALUE'
        /** @enum {string} */
        description?: 'The value of a field is invalid.'
      }[]
    }
    401: {
      details?: {
        /** @enum {string} */
        issue?: 'INVALID_ACCOUNT_STATUS'
        /** @enum {string} */
        description?: 'Account validations failed for the user.'
      }[]
    }
    403: {
      details?: {
        /** @enum {string} */
        issue?: 'PERMISSION_DENIED'
        /** @enum {string} */
        description?: 'You do not have permission to access or perform operations on this resource.'
      }[]
    }
    404: {
      details?: {
        /** @enum {string} */
        issue?: 'INVALID_RESOURCE_ID'
        /** @enum {string} */
        description?: 'Specified resource ID does not exist. Please check the resource ID and try again.'
      }[]
    }
    422: {
      details?: (
        | {
            /** @enum {string} */
            issue?: 'USER_ACCOUNT_CLOSED'
            /** @enum {string} */
            description?: 'User account locked or closed.'
          }
        | {
            /** @enum {string} */
            issue?: 'DUPLICATE_RESOURCE_IDENTIFIER'
            /** @enum {string} */
            description?: 'Identifier must be unique.'
          }
        | {
            /** @enum {string} */
            issue?: 'COUNTRY_NOT_SUPPORTED'
            /** @enum {string} */
            description?: 'This merchant country is not currently supported.'
          }
      )[]
    }
    /**
     * Error Details
     * @description The error details. Required for client-side `4XX` errors.
     */
    error_details: {
      /** @description The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors. */
      field?: string
      /** @description The value of the field that caused the error. */
      value?: string
      location?: components['schemas']['error_location']
      /** @description The unique, fine-grained application-level error code. */
      issue: string
      /** @description The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value. */
      description?: string
    }
    /**
     * @description The location of the field that caused the error. Value is `body`, `path`, or `query`.
     * @default body
     * @enum {string}
     */
    error_location: 'body' | 'path' | 'query'
    /** @description The default error response. */
    error_default:
      | components['schemas']['error_400']
      | components['schemas']['error_401']
      | components['schemas']['error_403']
      | components['schemas']['error_404']
      | components['schemas']['error_409']
      | components['schemas']['error_415']
      | components['schemas']['error_422']
      | components['schemas']['error_500']
      | components['schemas']['error_503']
    /**
     * Link Description
     * @description The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information.
     */
    error_link_description: {
      /** @description The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
      href: string
      /** @description The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
      rel: string
      /**
       * @description The HTTP method required to make the related call.
       * @enum {string}
       */
      method?: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'
    }
    /**
     * Bad Request Error
     * @description Request is not well-formed, syntactically incorrect, or violates schema.
     */
    error_400: {
      /** @enum {string} */
      name?: 'INVALID_REQUEST'
      /** @enum {string} */
      message?: 'Request is not well-formed, syntactically incorrect, or violates schema.'
      details?: components['schemas']['error_details'][]
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Unauthorized Error
     * @description Authentication failed due to missing Authorization header, or invalid authentication credentials.
     */
    error_401: {
      /** @enum {string} */
      name?: 'AUTHENTICATION_FAILURE'
      /** @enum {string} */
      message?: 'Authentication failed due to missing authorization header, or invalid authentication credentials.'
      details?: components['schemas']['error_details'][]
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Not Authorized Error
     * @description The client is not authorized to access this resource, although it may have valid credentials.
     */
    error_403: {
      /** @enum {string} */
      name?: 'NOT_AUTHORIZED'
      /** @enum {string} */
      message?: 'Authorization failed due to insufficient permissions.'
      details?: components['schemas']['error_details'][]
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Not found Error
     * @description The server has not found anything matching the request URI. This either means that the URI is incorrect or the resource is not available.
     */
    error_404: {
      /** @enum {string} */
      name?: 'RESOURCE_NOT_FOUND'
      /** @enum {string} */
      message?: 'The specified resource does not exist.'
      details?: components['schemas']['error_details'][]
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Resource Conflict Error
     * @description The server has detected a conflict while processing this request.
     */
    error_409: {
      /** @enum {string} */
      name?: 'RESOURCE_CONFLICT'
      /** @enum {string} */
      message?: 'The server has detected a conflict while processing this request.'
      details?: components['schemas']['error_details'][]
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Unsupported Media Type Error
     * @description The server does not support the request payload's media type.
     */
    error_415: {
      /** @enum {string} */
      name?: 'UNSUPPORTED_MEDIA_TYPE'
      /** @enum {string} */
      message?: "The server does not support the request payload's media type."
      details?: components['schemas']['error_details'][]
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Unprocessable Entity Error
     * @description The requested action cannot be performed and may require interaction with APIs or processes outside of the current request. This is distinct from a 500 response in that there are no systemic problems limiting the API from performing the request.
     */
    error_422: {
      /** @enum {string} */
      name?: 'UNPROCESSABLE_ENTITY'
      /** @enum {string} */
      message?: 'The requested action could not be performed, semantically incorrect, or failed business validation.'
      details?: components['schemas']['error_details'][]
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Internal Server Error
     * @description This is either a system or application error, and generally indicates that although the client appeared to provide a correct request, something unexpected has gone wrong on the server.
     * @example {
     *       "name": "INTERNAL_SERVER_ERROR",
     *       "message": "An internal server error occurred.",
     *       "debug_id": "90957fca61718",
     *       "links": [
     *         {
     *           "href": "https://developer.paypal.com/api/orders/v2/#error-INTERNAL_SERVER_ERROR",
     *           "rel": "information_link"
     *         }
     *       ]
     *     }
     */
    error_500: {
      /** @enum {string} */
      name?: 'INTERNAL_SERVER_ERROR'
      /** @enum {string} */
      message?: 'An internal server error occurred.'
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Service Unavailable Error
     * @description The server is temporarily unable to handle the request, for example, because of planned maintenance or downtime.
     * @example {
     *       "name": "SERVICE_UNAVAILABLE",
     *       "message": "Service Unavailable.",
     *       "debug_id": "90957fca61718",
     *       "information_link": "https://developer.paypal.com/docs/api/orders/v2/#error-SERVICE_UNAVAILABLE"
     *     }
     */
    error_503: {
      /** @enum {string} */
      name?: 'SERVICE_UNAVAILABLE'
      /** @enum {string} */
      message?: 'Service Unavailable.'
      /** @description The PayPal internal ID. Used for correlation purposes. */
      debug_id?: string
      /** @description An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS). */
      links?: components['schemas']['error_link_description'][]
    }
    /**
     * Format: ppaas_date_time_v3
     * @description The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
     */
    date_time: string
    /**
     * Link Description
     * @description The request-related [HATEOAS link](/docs/api/reference/api-responses/#hateoas-links) information.
     */
    link_description: {
      /** @description The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
      href: string
      /** @description The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
      rel: string
      /**
       * @description The HTTP method required to make the related call.
       * @enum {string}
       */
      method?: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'HEAD' | 'CONNECT' | 'OPTIONS' | 'PATCH'
    }
    /**
     * Product Element
     * @description The details for a product in the collection response.
     */
    product_collection_element: {
      /** @description The ID of the product. */
      readonly id?: string
      /** @description The product name. */
      name?: string
      /** @description The product description. */
      description?: string
      /** @description The date and time when the product was created, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). */
      readonly create_time?: components['schemas']['date_time']
      /** @description An array of request-related [HATEOAS links](/docs/api/overview/#hateoas-links). */
      readonly links?: components['schemas']['link_description'][]
    }
    /**
     * Product Collection
     * @description The list of products, with details.
     */
    product_collection: {
      /** @description An array of products. */
      products?: components['schemas']['product_collection_element'][]
      /** @description The total number of items. */
      total_items?: number
      /** @description The total number of pages. */
      total_pages?: number
      /** @description An array of request-related [HATEOAS links](/docs/api/overview/#hateoas-links). */
      readonly links?: components['schemas']['link_description'][]
    }
    /**
     * Product Category
     * @description The product category.
     * @enum {string}
     */
    product_category:
      | 'AC_REFRIGERATION_REPAIR'
      | 'ACADEMIC_SOFTWARE'
      | 'ACCESSORIES'
      | 'ACCOUNTING'
      | 'ADULT'
      | 'ADVERTISING'
      | 'AFFILIATED_AUTO_RENTAL'
      | 'AGENCIES'
      | 'AGGREGATORS'
      | 'AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER'
      | 'AIR_CARRIERS_AIRLINES'
      | 'AIRLINES'
      | 'AIRPORTS_FLYING_FIELDS'
      | 'ALCOHOLIC_BEVERAGES'
      | 'AMUSEMENT_PARKS_CARNIVALS'
      | 'ANIMATION'
      | 'ANTIQUES'
      | 'APPLIANCES'
      | 'AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS'
      | 'ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES'
      | 'ART_AND_CRAFT_SUPPLIES'
      | 'ART_DEALERS_AND_GALLERIES'
      | 'ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS'
      | 'ARTS_AND_CRAFTS'
      | 'ARTS_CRAFTS_AND_COLLECTIBLES'
      | 'AUDIO_BOOKS'
      | 'AUTO_ASSOCIATIONS_CLUBS'
      | 'AUTO_DEALER_USED_ONLY'
      | 'AUTO_RENTALS'
      | 'AUTO_SERVICE'
      | 'AUTOMATED_FUEL_DISPENSERS'
      | 'AUTOMOBILE_ASSOCIATIONS'
      | 'AUTOMOTIVE'
      | 'AUTOMOTIVE_REPAIR_SHOPS_NON_DEALER'
      | 'AUTOMOTIVE_TOP_AND_BODY_SHOPS'
      | 'AVIATION'
      | 'BABIES_CLOTHING_AND_SUPPLIES'
      | 'BABY'
      | 'BANDS_ORCHESTRAS_ENTERTAINERS'
      | 'BARBIES'
      | 'BATH_AND_BODY'
      | 'BATTERIES'
      | 'BEAN_BABIES'
      | 'BEAUTY'
      | 'BEAUTY_AND_FRAGRANCES'
      | 'BED_AND_BATH'
      | 'BICYCLE_SHOPS_SALES_AND_SERVICE'
      | 'BICYCLES_AND_ACCESSORIES'
      | 'BILLIARD_POOL_ESTABLISHMENTS'
      | 'BOAT_DEALERS'
      | 'BOAT_RENTALS_AND_LEASING'
      | 'BOATING_SAILING_AND_ACCESSORIES'
      | 'BOOKS'
      | 'BOOKS_AND_MAGAZINES'
      | 'BOOKS_MANUSCRIPTS'
      | 'BOOKS_PERIODICALS_AND_NEWSPAPERS'
      | 'BOWLING_ALLEYS'
      | 'BULLETIN_BOARD'
      | 'BUS_LINE'
      | 'BUS_LINES_CHARTERS_TOUR_BUSES'
      | 'BUSINESS'
      | 'BUSINESS_AND_SECRETARIAL_SCHOOLS'
      | 'BUYING_AND_SHOPPING_SERVICES_AND_CLUBS'
      | 'CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES'
      | 'CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO'
      | 'CAMERA_AND_PHOTOGRAPHIC_SUPPLIES'
      | 'CAMERAS'
      | 'CAMERAS_AND_PHOTOGRAPHY'
      | 'CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS'
      | 'CAMPING_AND_OUTDOORS'
      | 'CAMPING_AND_SURVIVAL'
      | 'CAR_AND_TRUCK_DEALERS'
      | 'CAR_AND_TRUCK_DEALERS_USED_ONLY'
      | 'CAR_AUDIO_AND_ELECTRONICS'
      | 'CAR_RENTAL_AGENCY'
      | 'CATALOG_MERCHANT'
      | 'CATALOG_RETAIL_MERCHANT'
      | 'CATERING_SERVICES'
      | 'CHARITY'
      | 'CHECK_CASHIER'
      | 'CHILD_CARE_SERVICES'
      | 'CHILDREN_BOOKS'
      | 'CHIROPODISTS_PODIATRISTS'
      | 'CHIROPRACTORS'
      | 'CIGAR_STORES_AND_STANDS'
      | 'CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS'
      | 'CIVIL_SOCIAL_FRAT_ASSOCIATIONS'
      | 'CLOTHING'
      | 'CLOTHING_ACCESSORIES_AND_SHOES'
      | 'CLOTHING_RENTAL'
      | 'COFFEE_AND_TEA'
      | 'COIN_OPERATED_BANKS_AND_CASINOS'
      | 'COLLECTIBLES'
      | 'COLLECTION_AGENCY'
      | 'COLLEGES_AND_UNIVERSITIES'
      | 'COMMERCIAL_EQUIPMENT'
      | 'COMMERCIAL_FOOTWEAR'
      | 'COMMERCIAL_PHOTOGRAPHY'
      | 'COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS'
      | 'COMMERCIAL_SPORTS_PROFESSIONA'
      | 'COMMODITIES_AND_FUTURES_EXCHANGE'
      | 'COMPUTER_AND_DATA_PROCESSING_SERVICES'
      | 'COMPUTER_HARDWARE_AND_SOFTWARE'
      | 'COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS'
      | 'CONSTRUCTION'
      | 'CONSTRUCTION_MATERIALS_NOT_ELSEWHERE_CLASSIFIED'
      | 'CONSULTING_SERVICES'
      | 'CONSUMER_CREDIT_REPORTING_AGENCIES'
      | 'CONVALESCENT_HOMES'
      | 'COSMETIC_STORES'
      | 'COUNSELING_SERVICES_DEBT_MARRIAGE_PERSONAL'
      | 'COUNTERFEIT_CURRENCY_AND_STAMPS'
      | 'COUNTERFEIT_ITEMS'
      | 'COUNTRY_CLUBS'
      | 'COURIER_SERVICES'
      | 'COURIER_SERVICES_AIR_AND_GROUND_AND_FREIGHT_FORWARDERS'
      | 'COURT_COSTS_ALIMNY_CHILD_SUPT'
      | 'COURT_COSTS_INCLUDING_ALIMONY_AND_CHILD_SUPPORT_COURTS_OF_LAW'
      | 'CREDIT_CARDS'
      | 'CREDIT_UNION'
      | 'CULTURE_AND_RELIGION'
      | 'DAIRY_PRODUCTS_STORES'
      | 'DANCE_HALLS_STUDIOS_AND_SCHOOLS'
      | 'DECORATIVE'
      | 'DENTAL'
      | 'DENTISTS_AND_ORTHODONTISTS'
      | 'DEPARTMENT_STORES'
      | 'DESKTOP_PCS'
      | 'DEVICES'
      | 'DIECAST_TOYS_VEHICLES'
      | 'DIGITAL_GAMES'
      | 'DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC'
      | 'DIRECT_MARKETING'
      | 'DIRECT_MARKETING_CATALOG_MERCHANT'
      | 'DIRECT_MARKETING_INBOUND_TELE'
      | 'DIRECT_MARKETING_OUTBOUND_TELE'
      | 'DIRECT_MARKETING_SUBSCRIPTION'
      | 'DISCOUNT_STORES'
      | 'DOOR_TO_DOOR_SALES'
      | 'DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY'
      | 'DRINKING_PLACES'
      | 'DRUGSTORE'
      | 'DURABLE_GOODS'
      | 'ECOMMERCE_DEVELOPMENT'
      | 'ECOMMERCE_SERVICES'
      | 'EDUCATIONAL_AND_TEXTBOOKS'
      | 'ELECTRIC_RAZOR_STORES'
      | 'ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR'
      | 'ELECTRICAL_CONTRACTORS'
      | 'ELECTRICAL_PARTS_AND_EQUIPMENT'
      | 'ELECTRONIC_CASH'
      | 'ELEMENTARY_AND_SECONDARY_SCHOOLS'
      | 'EMPLOYMENT'
      | 'ENTERTAINERS'
      | 'ENTERTAINMENT_AND_MEDIA'
      | 'EQUIP_TOOL_FURNITURE_AND_APPLIANCE_RENTAL_AND_LEASING'
      | 'ESCROW'
      | 'EVENT_AND_WEDDING_PLANNING'
      | 'EXERCISE_AND_FITNESS'
      | 'EXERCISE_EQUIPMENT'
      | 'EXTERMINATING_AND_DISINFECTING_SERVICES'
      | 'FABRICS_AND_SEWING'
      | 'FAMILY_CLOTHING_STORES'
      | 'FASHION_JEWELRY'
      | 'FAST_FOOD_RESTAURANTS'
      | 'FICTION_AND_NONFICTION'
      | 'FINANCE_COMPANY'
      | 'FINANCIAL_AND_INVESTMENT_ADVICE'
      | 'FINANCIAL_INSTITUTIONS_MERCHANDISE_AND_SERVICES'
      | 'FIREARM_ACCESSORIES'
      | 'FIREARMS_WEAPONS_AND_KNIVES'
      | 'FIREPLACE_AND_FIREPLACE_SCREENS'
      | 'FIREWORKS'
      | 'FISHING'
      | 'FLORISTS'
      | 'FLOWERS'
      | 'FOOD_DRINK_AND_NUTRITION'
      | 'FOOD_PRODUCTS'
      | 'FOOD_RETAIL_AND_SERVICE'
      | 'FRAGRANCES_AND_PERFUMES'
      | 'FREEZER_AND_LOCKER_MEAT_PROVISIONERS'
      | 'FUEL_DEALERS_FUEL_OIL_WOOD_AND_COAL'
      | 'FUEL_DEALERS_NON_AUTOMOTIVE'
      | 'FUNERAL_SERVICES_AND_CREMATORIES'
      | 'FURNISHING_AND_DECORATING'
      | 'FURNITURE'
      | 'FURRIERS_AND_FUR_SHOPS'
      | 'GADGETS_AND_OTHER_ELECTRONICS'
      | 'GAMBLING'
      | 'GAME_SOFTWARE'
      | 'GAMES'
      | 'GARDEN_SUPPLIES'
      | 'GENERAL'
      | 'GENERAL_CONTRACTORS'
      | 'GENERAL_GOVERNMENT'
      | 'GENERAL_SOFTWARE'
      | 'GENERAL_TELECOM'
      | 'GIFTS_AND_FLOWERS'
      | 'GLASS_PAINT_AND_WALLPAPER_STORES'
      | 'GLASSWARE_CRYSTAL_STORES'
      | 'GOVERNMENT'
      | 'GOVERNMENT_IDS_AND_LICENSES'
      | 'GOVERNMENT_LICENSED_ON_LINE_CASINOS_ON_LINE_GAMBLING'
      | 'GOVERNMENT_OWNED_LOTTERIES'
      | 'GOVERNMENT_SERVICES'
      | 'GRAPHIC_AND_COMMERCIAL_DESIGN'
      | 'GREETING_CARDS'
      | 'GROCERY_STORES_AND_SUPERMARKETS'
      | 'HARDWARE_AND_TOOLS'
      | 'HARDWARE_EQUIPMENT_AND_SUPPLIES'
      | 'HAZARDOUS_RESTRICTED_AND_PERISHABLE_ITEMS'
      | 'HEALTH_AND_BEAUTY_SPAS'
      | 'HEALTH_AND_NUTRITION'
      | 'HEALTH_AND_PERSONAL_CARE'
      | 'HEARING_AIDS_SALES_AND_SUPPLIES'
      | 'HEATING_PLUMBING_AC'
      | 'HIGH_RISK_MERCHANT'
      | 'HIRING_SERVICES'
      | 'HOBBIES_TOYS_AND_GAMES'
      | 'HOME_AND_GARDEN'
      | 'HOME_AUDIO'
      | 'HOME_DECOR'
      | 'HOME_ELECTRONICS'
      | 'HOSPITALS'
      | 'HOTELS_MOTELS_INNS_RESORTS'
      | 'HOUSEWARES'
      | 'HUMAN_PARTS_AND_REMAINS'
      | 'HUMOROUS_GIFTS_AND_NOVELTIES'
      | 'HUNTING'
      | 'IDS_LICENSES_AND_PASSPORTS'
      | 'ILLEGAL_DRUGS_AND_PARAPHERNALIA'
      | 'INDUSTRIAL'
      | 'INDUSTRIAL_AND_MANUFACTURING_SUPPLIES'
      | 'INSURANCE_AUTO_AND_HOME'
      | 'INSURANCE_DIRECT'
      | 'INSURANCE_LIFE_AND_ANNUITY'
      | 'INSURANCE_SALES_UNDERWRITING'
      | 'INSURANCE_UNDERWRITING_PREMIUMS'
      | 'INTERNET_AND_NETWORK_SERVICES'
      | 'INTRA_COMPANY_PURCHASES'
      | 'LABORATORIES_DENTAL_MEDICAL'
      | 'LANDSCAPING'
      | 'LANDSCAPING_AND_HORTICULTURAL_SERVICES'
      | 'LAUNDRY_CLEANING_SERVICES'
      | 'LEGAL'
      | 'LEGAL_SERVICES_AND_ATTORNEYS'
      | 'LOCAL_DELIVERY_SERVICE'
      | 'LOCKSMITH'
      | 'LODGING_AND_ACCOMMODATIONS'
      | 'LOTTERY_AND_CONTESTS'
      | 'LUGGAGE_AND_LEATHER_GOODS'
      | 'LUMBER_AND_BUILDING_MATERIALS'
      | 'MAGAZINES'
      | 'MAINTENANCE_AND_REPAIR_SERVICES'
      | 'MAKEUP_AND_COSMETICS'
      | 'MANUAL_CASH_DISBURSEMENTS'
      | 'MASSAGE_PARLORS'
      | 'MEDICAL'
      | 'MEDICAL_AND_PHARMACEUTICAL'
      | 'MEDICAL_CARE'
      | 'MEDICAL_EQUIPMENT_AND_SUPPLIES'
      | 'MEDICAL_SERVICES'
      | 'MEETING_PLANNERS'
      | 'MEMBERSHIP_CLUBS_AND_ORGANIZATIONS'
      | 'MEMBERSHIP_COUNTRY_CLUBS_GOLF'
      | 'MEMORABILIA'
      | 'MEN_AND_BOY_CLOTHING_AND_ACCESSORY_STORES'
      | 'MEN_CLOTHING'
      | 'MERCHANDISE'
      | 'METAPHYSICAL'
      | 'MILITARIA'
      | 'MILITARY_AND_CIVIL_SERVICE_UNIFORMS'
      | 'MISC._AUTOMOTIVE_AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS'
      | 'MISC._GENERAL_MERCHANDISE'
      | 'MISCELLANEOUS_GENERAL_SERVICES'
      | 'MISCELLANEOUS_REPAIR_SHOPS_AND_RELATED_SERVICES'
      | 'MODEL_KITS'
      | 'MONEY_TRANSFER_MEMBER_FINANCIAL_INSTITUTION'
      | 'MONEY_TRANSFER_MERCHANT'
      | 'MOTION_PICTURE_THEATERS'
      | 'MOTOR_FREIGHT_CARRIERS_AND_TRUCKING'
      | 'MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL'
      | 'MOTOR_HOMES_DEALERS'
      | 'MOTOR_VEHICLE_SUPPLIES_AND_NEW_PARTS'
      | 'MOTORCYCLE_DEALERS'
      | 'MOTORCYCLES'
      | 'MOVIE'
      | 'MOVIE_TICKETS'
      | 'MOVING_AND_STORAGE'
      | 'MULTI_LEVEL_MARKETING'
      | 'MUSIC_CDS_CASSETTES_AND_ALBUMS'
      | 'MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC'
      | 'NETWORKING'
      | 'NEW_AGE'
      | 'NEW_PARTS_AND_SUPPLIES_MOTOR_VEHICLE'
      | 'NEWS_DEALERS_AND_NEWSTANDS'
      | 'NON_DURABLE_GOODS'
      | 'NON_FICTION'
      | 'NON_PROFIT_POLITICAL_AND_RELIGION'
      | 'NONPROFIT'
      | 'NOVELTIES'
      | 'OEM_SOFTWARE'
      | 'OFFICE_SUPPLIES_AND_EQUIPMENT'
      | 'ONLINE_DATING'
      | 'ONLINE_GAMING'
      | 'ONLINE_GAMING_CURRENCY'
      | 'ONLINE_SERVICES'
      | 'OOUTBOUND_TELEMARKETING_MERCH'
      | 'OPHTHALMOLOGISTS_OPTOMETRIST'
      | 'OPTICIANS_AND_DISPENSING'
      | 'ORTHOPEDIC_GOODS_PROSTHETICS'
      | 'OSTEOPATHS'
      | 'OTHER'
      | 'PACKAGE_TOUR_OPERATORS'
      | 'PAINTBALL'
      | 'PAINTS_VARNISHES_AND_SUPPLIES'
      | 'PARKING_LOTS_AND_GARAGES'
      | 'PARTS_AND_ACCESSORIES'
      | 'PAWN_SHOPS'
      | 'PAYCHECK_LENDER_OR_CASH_ADVANCE'
      | 'PERIPHERALS'
      | 'PERSONALIZED_GIFTS'
      | 'PET_SHOPS_PET_FOOD_AND_SUPPLIES'
      | 'PETROLEUM_AND_PETROLEUM_PRODUCTS'
      | 'PETS_AND_ANIMALS'
      | 'PHOTOFINISHING_LABORATORIES_PHOTO_DEVELOPING'
      | 'PHOTOGRAPHIC_STUDIOS_PORTRAITS'
      | 'PHOTOGRAPHY'
      | 'PHYSICAL_GOOD'
      | 'PICTURE_VIDEO_PRODUCTION'
      | 'PIECE_GOODS_NOTIONS_AND_OTHER_DRY_GOODS'
      | 'PLANTS_AND_SEEDS'
      | 'PLUMBING_AND_HEATING_EQUIPMENTS_AND_SUPPLIES'
      | 'POLICE_RELATED_ITEMS'
      | 'POLITICAL_ORGANIZATIONS'
      | 'POSTAL_SERVICES_GOVERNMENT_ONLY'
      | 'POSTERS'
      | 'PREPAID_AND_STORED_VALUE_CARDS'
      | 'PRESCRIPTION_DRUGS'
      | 'PROMOTIONAL_ITEMS'
      | 'PUBLIC_WAREHOUSING_AND_STORAGE'
      | 'PUBLISHING_AND_PRINTING'
      | 'PUBLISHING_SERVICES'
      | 'RADAR_DECTORS'
      | 'RADIO_TELEVISION_AND_STEREO_REPAIR'
      | 'REAL_ESTATE'
      | 'REAL_ESTATE_AGENT'
      | 'REAL_ESTATE_AGENTS_AND_MANAGERS_RENTALS'
      | 'RELIGION_AND_SPIRITUALITY_FOR_PROFIT'
      | 'RELIGIOUS'
      | 'RELIGIOUS_ORGANIZATIONS'
      | 'REMITTANCE'
      | 'RENTAL_PROPERTY_MANAGEMENT'
      | 'RESIDENTIAL'
      | 'RETAIL'
      | 'RETAIL_FINE_JEWELRY_AND_WATCHES'
      | 'REUPHOLSTERY_AND_FURNITURE_REPAIR'
      | 'RINGS'
      | 'ROOFING_SIDING_SHEET_METAL'
      | 'RUGS_AND_CARPETS'
      | 'SCHOOLS_AND_COLLEGES'
      | 'SCIENCE_FICTION'
      | 'SCRAPBOOKING'
      | 'SCULPTURES'
      | 'SECURITIES_BROKERS_AND_DEALERS'
      | 'SECURITY_AND_SURVEILLANCE'
      | 'SECURITY_AND_SURVEILLANCE_EQUIPMENT'
      | 'SECURITY_BROKERS_AND_DEALERS'
      | 'SEMINARS'
      | 'SERVICE_STATIONS'
      | 'SERVICES'
      | 'SEWING_NEEDLEWORK_FABRIC_AND_PIECE_GOODS_STORES'
      | 'SHIPPING_AND_PACKING'
      | 'SHOE_REPAIR_HAT_CLEANING'
      | 'SHOE_STORES'
      | 'SHOES'
      | 'SNOWMOBILE_DEALERS'
      | 'SOFTWARE'
      | 'SPECIALTY_AND_MISC._FOOD_STORES'
      | 'SPECIALTY_CLEANING_POLISHING_AND_SANITATION_PREPARATIONS'
      | 'SPECIALTY_OR_RARE_PETS'
      | 'SPORT_GAMES_AND_TOYS'
      | 'SPORTING_AND_RECREATIONAL_CAMPS'
      | 'SPORTING_GOODS'
      | 'SPORTS_AND_OUTDOORS'
      | 'SPORTS_AND_RECREATION'
      | 'STAMP_AND_COIN'
      | 'STATIONARY_PRINTING_AND_WRITING_PAPER'
      | 'STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES'
      | 'STOCKS_BONDS_SECURITIES_AND_RELATED_CERTIFICATES'
      | 'STORED_VALUE_CARDS'
      | 'SUPPLIES'
      | 'SUPPLIES_AND_TOYS'
      | 'SURVEILLANCE_EQUIPMENT'
      | 'SWIMMING_POOLS_AND_SPAS'
      | 'SWIMMING_POOLS_SALES_SUPPLIES_SERVICES'
      | 'TAILORS_AND_ALTERATIONS'
      | 'TAX_PAYMENTS'
      | 'TAX_PAYMENTS_GOVERNMENT_AGENCIES'
      | 'TAXICABS_AND_LIMOUSINES'
      | 'TELECOMMUNICATION_SERVICES'
      | 'TELEPHONE_CARDS'
      | 'TELEPHONE_EQUIPMENT'
      | 'TELEPHONE_SERVICES'
      | 'THEATER'
      | 'TIRE_RETREADING_AND_REPAIR'
      | 'TOLL_OR_BRIDGE_FEES'
      | 'TOOLS_AND_EQUIPMENT'
      | 'TOURIST_ATTRACTIONS_AND_EXHIBITS'
      | 'TOWING_SERVICE'
      | 'TOYS_AND_GAMES'
      | 'TRADE_AND_VOCATIONAL_SCHOOLS'
      | 'TRADEMARK_INFRINGEMENT'
      | 'TRAILER_PARKS_AND_CAMPGROUNDS'
      | 'TRAINING_SERVICES'
      | 'TRANSPORTATION_SERVICES'
      | 'TRAVEL'
      | 'TRUCK_AND_UTILITY_TRAILER_RENTALS'
      | 'TRUCK_STOP'
      | 'TYPESETTING_PLATE_MAKING_AND_RELATED_SERVICES'
      | 'USED_MERCHANDISE_AND_SECONDHAND_STORES'
      | 'USED_PARTS_MOTOR_VEHICLE'
      | 'UTILITIES'
      | 'UTILITIES_ELECTRIC_GAS_WATER_SANITARY'
      | 'VARIETY_STORES'
      | 'VEHICLE_SALES'
      | 'VEHICLE_SERVICE_AND_ACCESSORIES'
      | 'VIDEO_EQUIPMENT'
      | 'VIDEO_GAME_ARCADES_ESTABLISH'
      | 'VIDEO_GAMES_AND_SYSTEMS'
      | 'VIDEO_TAPE_RENTAL_STORES'
      | 'VINTAGE_AND_COLLECTIBLE_VEHICLES'
      | 'VINTAGE_AND_COLLECTIBLES'
      | 'VITAMINS_AND_SUPPLEMENTS'
      | 'VOCATIONAL_AND_TRADE_SCHOOLS'
      | 'WATCH_CLOCK_AND_JEWELRY_REPAIR'
      | 'WEB_HOSTING_AND_DESIGN'
      | 'WELDING_REPAIR'
      | 'WHOLESALE_CLUBS'
      | 'WHOLESALE_FLORIST_SUPPLIERS'
      | 'WHOLESALE_PRESCRIPTION_DRUGS'
      | 'WILDLIFE_PRODUCTS'
      | 'WIRE_TRANSFER'
      | 'WIRE_TRANSFER_AND_MONEY_ORDER'
      | 'WOMEN_ACCESSORY_SPECIALITY'
      | 'WOMEN_CLOTHING'
    /**
     * Create Product Request
     * @description The create product request details.
     */
    product_request_POST: {
      /** @description The ID of the product. You can specify the SKU for the product. If you omit the ID, the system generates it. System-generated IDs have the `PROD-` prefix. */
      id?: string
      /** @description The product name. */
      name: string
      /** @description The product description. */
      description?: string
      /**
       * @description The product type. Indicates whether the product is physical or digital goods, or a service.
       * @default PHYSICAL
       * @enum {string}
       */
      type: 'PHYSICAL' | 'DIGITAL' | 'SERVICE'
      category?: components['schemas']['product_category']
      /**
       * Format: uri
       * @description The image URL for the product.
       */
      image_url?: string
      /**
       * Format: uri
       * @description The home page URL for the product.
       */
      home_url?: string
    }
    /**
     * Product Details
     * @description The product details.
     */
    product: {
      /** @description The ID of the product. */
      id?: string
      /** @description The product name. */
      name?: string
      /** @description The product description. */
      description?: string
      /**
       * @description The product type. Indicates whether the product is physical or digital goods, or a service.
       * @default PHYSICAL
       * @enum {string}
       */
      type: 'PHYSICAL' | 'DIGITAL' | 'SERVICE'
      category?: components['schemas']['product_category']
      /**
       * Format: uri
       * @description The image URL for the product.
       */
      image_url?: string
      /**
       * Format: uri
       * @description The home page URL for the product.
       */
      home_url?: string
      /** @description The date and time when the product was created, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). */
      readonly create_time?: components['schemas']['date_time']
      /** @description The date and time when the product was last updated, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). */
      readonly update_time?: components['schemas']['date_time']
      /** @description An array of request-related [HATEOAS links](/docs/api/overview/#hateoas-links). */
      readonly links?: components['schemas']['link_description'][]
    }
    'products.create-400': {
      details?: (
        | {
            /** @enum {string} */
            issue?: 'INVALID_PARAMETER_SYNTAX'
            /** @enum {string} */
            description?: 'Input identifier must not use system prefix(PROD-).'
          }
        | {
            /** @enum {string} */
            issue?: 'INVALID_PARAMETER_SYNTAX'
            /** @enum {string} */
            description?: 'The value of a field does not conform to the expected format.'
          }
        | {
            /** @enum {string} */
            issue?: 'INVALID_PARAMETER_VALUE'
            /** @enum {string} */
            description?: 'The value of a field is invalid.'
          }
        | {
            /** @enum {string} */
            issue?: 'MISSING_REQUIRED_PARAMETER'
            /** @enum {string} */
            description?: 'A required field is missing.'
          }
        | {
            /** @enum {string} */
            issue?: 'INVALID_STRING_MIN_LENGTH'
            /** @enum {string} */
            description?: 'The value of a field is too short.'
          }
        | {
            /** @enum {string} */
            issue?: 'INVALID_STRING_MAX_LENGTH'
            /** @enum {string} */
            description?: 'The value of a field is too long.'
          }
      )[]
    }
    /**
     * Patch
     * @description The JSON patch object to apply partial updates to resources.
     */
    patch: {
      /**
       * @description The operation.
       * @enum {string}
       */
      op: 'add' | 'remove' | 'replace' | 'move' | 'copy' | 'test'
      /** @description The <a href="https://tools.ietf.org/html/rfc6901">JSON Pointer</a> to the target document location at which to complete the operation. */
      path?: string
      /**
       * Patch Value
       * @description The value to apply. The <code>remove</code> operation does not require a value.
       */
      value?: unknown
      /** @description The <a href="https://tools.ietf.org/html/rfc6901">JSON Pointer</a> to the target document location from which to move the value. Required for the <code>move</code> operation. */
      from?: string
    }
    /**
     * Patch Request
     * @description An array of JSON patch objects to apply partial updates to resources.
     */
    patch_request: components['schemas']['patch'][]
    'products.patch-400': {
      details?: (
        | {
            /** @enum {string} */
            issue?: 'MISSING_REQUIRED_PARAMETER'
            /** @enum {string} */
            description?: 'A required field is missing.'
          }
        | {
            /** @enum {string} */
            issue?: 'UNSUPPORTED_PATCH_OPERATION'
            /** @enum {string} */
            description?: 'The specified patch operation not supported for this field.'
          }
        | {
            /** @enum {string} */
            issue?: 'INVALID_PATCH_PATH'
            /** @enum {string} */
            description?: 'The specified field cannot be patched.'
          }
        | {
            /** @enum {string} */
            issue?: 'INVALID_PARAMETER_SYNTAX'
            /** @enum {string} */
            description?: 'The value of a field does not conform to the expected format.'
          }
        | {
            /** @enum {string} */
            issue?: 'INVALID_PARAMETER_VALUE'
            /** @enum {string} */
            description?: 'The value of a field is invalid.'
          }
      )[]
    }
    'products.patch-422': {
      details?: (
        | {
            /** @enum {string} */
            issue?: 'USER_ACCOUNT_CLOSED'
            /** @enum {string} */
            description?: 'User account locked or closed.'
          }
        | {
            /** @enum {string} */
            issue?: 'DUPLICATE_RESOURCE_IDENTIFIER'
            /** @enum {string} */
            description?: 'Identifier must be unique.'
          }
      )[]
    }
  }
  responses: {
    /** @description The default response. */
    default: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['error_default']
      }
    }
  }
  parameters: {
    /** @description The preferred server response upon successful completion of the request. Value is:<ul><li><code>return=minimal</code>. The server returns a minimal response to optimize communication between the API caller and the server. A minimal response includes the <code>id</code>, <code>status</code> and HATEOAS links.</li><li><code>return=representation</code>. The server returns a complete resource representation, including the current state of the resource.</li></ul> */
    prefer: string
    /** @description The server stores keys for 72 hours. */
    paypal_request_id: string
    /** @description The number of items to return in the response. */
    page_size: number
    /** @description A non-zero integer which is the start index of the entire list of items that are returned in the response. So, the combination of `page=1` and `page_size=20` returns the first 20 items. The combination of `page=2` and `page_size=20` returns the next 20 items. */
    page: number
    /** @description Indicates whether to show the total items and total pages in the response. */
    total_required: boolean
    /** @description The product ID. */
    product_id: string
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  'products.list': {
    parameters: {
      query?: {
        /** @description The number of items to return in the response. */
        page_size?: components['parameters']['page_size']
        /** @description A non-zero integer which is the start index of the entire list of items that are returned in the response. So, the combination of `page=1` and `page_size=20` returns the first 20 items. The combination of `page=2` and `page_size=20` returns the next 20 items. */
        page?: components['parameters']['page']
        /** @description Indicates whether to show the total items and total pages in the response. */
        total_required?: components['parameters']['total_required']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A successful request returns the HTTP `200 OK` status code and a JSON response body that lists products with details. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['product_collection']
        }
      }
      /** @description Bad Request. Request is not well-formed, syntactically incorrect, or violates schema. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_400'] & components['schemas']['400']
        }
      }
      /** @description Authentication failed due to missing authorization header, or invalid authentication credentials. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_401'] & components['schemas']['401']
        }
      }
      /** @description Authorization failed due to insufficient permissions. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_403'] & components['schemas']['403']
        }
      }
      /** @description An internal server error has occurred. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_500']
        }
      }
      default: components['responses']['default']
    }
  }
  'products.create': {
    parameters: {
      query?: never
      header?: {
        /** @description The preferred server response upon successful completion of the request. Value is:<ul><li><code>return=minimal</code>. The server returns a minimal response to optimize communication between the API caller and the server. A minimal response includes the <code>id</code>, <code>status</code> and HATEOAS links.</li><li><code>return=representation</code>. The server returns a complete resource representation, including the current state of the resource.</li></ul> */
        Prefer?: components['parameters']['prefer']
        /** @description The server stores keys for 72 hours. */
        'PayPal-Request-Id'?: components['parameters']['paypal_request_id']
      }
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['product_request_POST']
      }
    }
    responses: {
      /** @description A successful request returns the HTTP `200 OK` status code and a JSON response body that shows product details. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['product']
        }
      }
      /** @description A successful request returns the HTTP `201 Created` status code and a JSON response body that shows product details. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['product']
        }
      }
      /** @description Bad Request. Request is not well-formed, syntactically incorrect, or violates schema. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_400'] & components['schemas']['products.create-400']
        }
      }
      /** @description Authentication failed due to missing authorization header, or invalid authentication credentials. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_401'] & components['schemas']['401']
        }
      }
      /** @description Authorization failed due to insufficient permissions. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_403'] & components['schemas']['403']
        }
      }
      /** @description The requested action could not be performed, semantically incorrect, or failed business validation. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_422'] & components['schemas']['422']
        }
      }
      /** @description An internal server error has occurred. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_500']
        }
      }
      default: components['responses']['default']
    }
  }
  'products.get': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The product ID. */
        product_id: components['parameters']['product_id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A successful request returns the HTTP `200 OK` status code and a JSON response body that shows product details. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['product']
        }
      }
      /** @description Authentication failed due to missing authorization header, or invalid authentication credentials. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_401'] & components['schemas']['401']
        }
      }
      /** @description Authorization failed due to insufficient permissions. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_403'] & components['schemas']['403']
        }
      }
      /** @description The specified resource does not exist. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_404'] & components['schemas']['404']
        }
      }
      /** @description An internal server error has occurred. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_500']
        }
      }
      default: components['responses']['default']
    }
  }
  'products.patch': {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The product ID. */
        product_id: components['parameters']['product_id']
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['patch_request']
      }
    }
    responses: {
      /** @description A successful request returns the HTTP `204 No Content` status code with no JSON response body. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request. Request is not well-formed, syntactically incorrect, or violates schema. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_400'] & components['schemas']['products.patch-400']
        }
      }
      /** @description Authentication failed due to missing authorization header, or invalid authentication credentials. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_401'] & components['schemas']['401']
        }
      }
      /** @description Authorization failed due to insufficient permissions. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_403'] & components['schemas']['403']
        }
      }
      /** @description The specified resource does not exist. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_404'] & components['schemas']['404']
        }
      }
      /** @description The requested action could not be performed, semantically incorrect, or failed business validation. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_422'] & components['schemas']['products.patch-422']
        }
      }
      /** @description An internal server error has occurred. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['error_500']
        }
      }
      default: components['responses']['default']
    }
  }
}
