name: Deployment

on:
  workflow_run:
    workflows: ['Node.js CI']
    types: [completed]
    branches: [main, ci/run-deployment-in-different-workflow] # TODO: remove test branch here

jobs:
  pulumi:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/pulumi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          version: 7
          run_install: true
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
          upsert: true
          work-dir: ./packages/pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}

  deploy:
    needs: [pulumi]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Deploy App
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: timebook
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  migrate:
    name: Migrate Database
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          version: 7
          run_install: true
      - name: Database migration
        run: pnpm run migrate-db
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
