name: Deploy to DigitalOcean

on:
  push:
    branches: [main, deploy-to-digitalocean]
  # workflow_run:
  #   workflows: Node.js CI
  #   branches: [main, deploy-to-digitalocean]
  #   types: completed

jobs:
  deploy:
    # `if` required because a workflow run is triggered regardless of
    # the result of the previous workflow (see the documentation page)
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: timebook-app
          token: abc123
          # token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
